# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('base_site_URL', models.URLField()),
                ('base_embed_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
                ('url', models.URLField()),
                ('host_code', models.CharField(blank=True, max_length=15, null=True)),
                ('thumbnail_image', models.ImageField(upload_to='uploads/thumbnails')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Project Type',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Project_type'),
        ),
    ]
